[package]
name = "hyoka"
version.workspace = true
edition.workspace = true

[workspace]
members = ["tiny-skia"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[dependencies]
concat-idents = "1.1.5"
iced = { version = "0.14.0", default-features = false, features = [
  "advanced",
  "canvas",
  "svg",
  "tiny-skia",
  "tokio",
  "wayland",
] }
iced_core = { version = "0.14.0", default-features = false }
iced_runtime = { version = "0.14.0", default-features = false }
iced_tiny_skia = { version = "0.14.0", default-features = false }
resvg = { version = "0.45.1", default-features = false }
rustc-hash = "2.1.1"
rustix = { version = "1.1.3", features = ["mm"] }
tiny-skia = { version = "0.11.4", default-features = false }
tokio = { version = "1.49.0", features = ["macros", "net", "rt", "sync"] }

[build-dependencies]
bindgen = { version = "0.72.1", features = [] }
cc = { version = "1.2.51", features = ["parallel"] }
